// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCflt44_5jyqfX9hhx6a0nKKJcQopHypA4',
    appId: '1:300262366202:web:ef097e0c5653e7a2966243',
    messagingSenderId: '300262366202',
    projectId: 'note-app-a36b8',
    authDomain: 'note-app-a36b8.firebaseapp.com',
    storageBucket: 'note-app-a36b8.appspot.com',
    measurementId: 'G-K1JPSH5XSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyxnoaYgchVE2ltiUzE27JoEk4Yh3aBkg',
    appId: '1:300262366202:android:b47e45ab3d54f7b6966243',
    messagingSenderId: '300262366202',
    projectId: 'note-app-a36b8',
    storageBucket: 'note-app-a36b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqqLRf3fyoUxX_7Ybqp8UP54hnLSAYTiU',
    appId: '1:300262366202:ios:ba3e619965f69772966243',
    messagingSenderId: '300262366202',
    projectId: 'note-app-a36b8',
    storageBucket: 'note-app-a36b8.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqqLRf3fyoUxX_7Ybqp8UP54hnLSAYTiU',
    appId: '1:300262366202:ios:623f442b2372dc1d966243',
    messagingSenderId: '300262366202',
    projectId: 'note-app-a36b8',
    storageBucket: 'note-app-a36b8.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
